// Code generated by ent, DO NOT EDIT.

package db

import (
	"fmt"
	"strings"
	"test/db/answer"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// Answer is the model entity for the Answer schema.
type Answer struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Text holds the value of the "text" field.
	Text string `json:"text,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the AnswerQuery when eager-loading is set.
	Edges        AnswerEdges `json:"edges"`
	selectValues sql.SelectValues
}

// AnswerEdges holds the relations/edges for other nodes in the graph.
type AnswerEdges struct {
	// Choices holds the value of the choices edge.
	Choices []*Choice `json:"choices,omitempty"`
	// SurveyQuestionAnswers holds the value of the survey_question_answers edge.
	SurveyQuestionAnswers []*SurveyQuestionAnswers `json:"survey_question_answers,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// ChoicesOrErr returns the Choices value or an error if the edge
// was not loaded in eager-loading.
func (e AnswerEdges) ChoicesOrErr() ([]*Choice, error) {
	if e.loadedTypes[0] {
		return e.Choices, nil
	}
	return nil, &NotLoadedError{edge: "choices"}
}

// SurveyQuestionAnswersOrErr returns the SurveyQuestionAnswers value or an error if the edge
// was not loaded in eager-loading.
func (e AnswerEdges) SurveyQuestionAnswersOrErr() ([]*SurveyQuestionAnswers, error) {
	if e.loadedTypes[1] {
		return e.SurveyQuestionAnswers, nil
	}
	return nil, &NotLoadedError{edge: "survey_question_answers"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Answer) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case answer.FieldText:
			values[i] = new(sql.NullString)
		case answer.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case answer.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Answer fields.
func (a *Answer) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case answer.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				a.ID = *value
			}
		case answer.FieldText:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field text", values[i])
			} else if value.Valid {
				a.Text = value.String
			}
		case answer.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				a.CreatedAt = value.Time
			}
		default:
			a.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Answer.
// This includes values selected through modifiers, order, etc.
func (a *Answer) Value(name string) (ent.Value, error) {
	return a.selectValues.Get(name)
}

// QueryChoices queries the "choices" edge of the Answer entity.
func (a *Answer) QueryChoices() *ChoiceQuery {
	return NewAnswerClient(a.config).QueryChoices(a)
}

// QuerySurveyQuestionAnswers queries the "survey_question_answers" edge of the Answer entity.
func (a *Answer) QuerySurveyQuestionAnswers() *SurveyQuestionAnswersQuery {
	return NewAnswerClient(a.config).QuerySurveyQuestionAnswers(a)
}

// Update returns a builder for updating this Answer.
// Note that you need to call Answer.Unwrap() before calling this method if this Answer
// was returned from a transaction, and the transaction was committed or rolled back.
func (a *Answer) Update() *AnswerUpdateOne {
	return NewAnswerClient(a.config).UpdateOne(a)
}

// Unwrap unwraps the Answer entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (a *Answer) Unwrap() *Answer {
	_tx, ok := a.config.driver.(*txDriver)
	if !ok {
		panic("db: Answer is not a transactional entity")
	}
	a.config.driver = _tx.drv
	return a
}

// String implements the fmt.Stringer.
func (a *Answer) String() string {
	var builder strings.Builder
	builder.WriteString("Answer(")
	builder.WriteString(fmt.Sprintf("id=%v, ", a.ID))
	builder.WriteString("text=")
	builder.WriteString(a.Text)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(a.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Answers is a parsable slice of Answer.
type Answers []*Answer
