// Code generated by ent, DO NOT EDIT.

package runtime

import (
	"test/db/answer"
	"test/db/customer"
	"test/db/project"
	"test/db/question"
	"test/db/schema"
	"test/db/schema/schematype"
	"test/db/survey"
	"test/db/surveyinvitation"
	"test/db/surveyquestionanswers"
	"time"

	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	answerFields := schema.Answer{}.Fields()
	_ = answerFields
	// answerDescCreatedAt is the schema descriptor for created_at field.
	answerDescCreatedAt := answerFields[2].Descriptor()
	// answer.DefaultCreatedAt holds the default value on creation for the created_at field.
	answer.DefaultCreatedAt = answerDescCreatedAt.Default.(func() time.Time)
	// answerDescID is the schema descriptor for id field.
	answerDescID := answerFields[0].Descriptor()
	// answer.DefaultID holds the default value on creation for the id field.
	answer.DefaultID = answerDescID.Default.(func() uuid.UUID)
	customerHooks := schema.Customer{}.Hooks()
	customer.Hooks[0] = customerHooks[0]
	customerFields := schema.Customer{}.Fields()
	_ = customerFields
	// customerDescCreatedAt is the schema descriptor for created_at field.
	customerDescCreatedAt := customerFields[6].Descriptor()
	// customer.DefaultCreatedAt holds the default value on creation for the created_at field.
	customer.DefaultCreatedAt = customerDescCreatedAt.Default.(func() time.Time)
	// customerDescUpdatedAt is the schema descriptor for updated_at field.
	customerDescUpdatedAt := customerFields[7].Descriptor()
	// customer.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	customer.DefaultUpdatedAt = customerDescUpdatedAt.Default.(func() time.Time)
	// customerDescID is the schema descriptor for id field.
	customerDescID := customerFields[0].Descriptor()
	// customer.DefaultID holds the default value on creation for the id field.
	customer.DefaultID = customerDescID.Default.(func() uuid.UUID)
	projectHooks := schema.Project{}.Hooks()
	project.Hooks[0] = projectHooks[0]
	projectFields := schema.Project{}.Fields()
	_ = projectFields
	// projectDescName is the schema descriptor for name field.
	projectDescName := projectFields[3].Descriptor()
	// project.NameValidator is a validator for the "name" field. It is called by the builders before save.
	project.NameValidator = projectDescName.Validators[0].(func(string) error)
	// projectDescDescription is the schema descriptor for description field.
	projectDescDescription := projectFields[4].Descriptor()
	// project.DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	project.DescriptionValidator = projectDescDescription.Validators[0].(func(string) error)
	// projectDescEstBudget is the schema descriptor for est_budget field.
	projectDescEstBudget := projectFields[5].Descriptor()
	// project.EstBudgetValidator is a validator for the "est_budget" field. It is called by the builders before save.
	project.EstBudgetValidator = projectDescEstBudget.Validators[0].(func(float64) error)
	// projectDescCreatedAt is the schema descriptor for created_at field.
	projectDescCreatedAt := projectFields[6].Descriptor()
	// project.DefaultCreatedAt holds the default value on creation for the created_at field.
	project.DefaultCreatedAt = projectDescCreatedAt.Default.(func() time.Time)
	// projectDescUpdatedAt is the schema descriptor for updated_at field.
	projectDescUpdatedAt := projectFields[7].Descriptor()
	// project.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	project.DefaultUpdatedAt = projectDescUpdatedAt.Default.(func() time.Time)
	// projectDescID is the schema descriptor for id field.
	projectDescID := projectFields[0].Descriptor()
	// project.DefaultID holds the default value on creation for the id field.
	project.DefaultID = projectDescID.Default.(func() uuid.UUID)
	questionHooks := schema.Question{}.Hooks()
	question.Hooks[0] = questionHooks[0]
	questionFields := schema.Question{}.Fields()
	_ = questionFields
	// questionDescWeight is the schema descriptor for weight field.
	questionDescWeight := questionFields[3].Descriptor()
	// question.DefaultWeight holds the default value on creation for the weight field.
	question.DefaultWeight = questionDescWeight.Default.(int)
	// questionDescRequired is the schema descriptor for required field.
	questionDescRequired := questionFields[4].Descriptor()
	// question.DefaultRequired holds the default value on creation for the required field.
	question.DefaultRequired = questionDescRequired.Default.(bool)
	// questionDescMeta is the schema descriptor for meta field.
	questionDescMeta := questionFields[5].Descriptor()
	// question.DefaultMeta holds the default value on creation for the meta field.
	question.DefaultMeta = questionDescMeta.Default.(*schematype.Metadata)
	// questionDescCreatedAt is the schema descriptor for created_at field.
	questionDescCreatedAt := questionFields[6].Descriptor()
	// question.DefaultCreatedAt holds the default value on creation for the created_at field.
	question.DefaultCreatedAt = questionDescCreatedAt.Default.(func() time.Time)
	// questionDescUpdatedAt is the schema descriptor for updated_at field.
	questionDescUpdatedAt := questionFields[7].Descriptor()
	// question.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	question.DefaultUpdatedAt = questionDescUpdatedAt.Default.(func() time.Time)
	// questionDescID is the schema descriptor for id field.
	questionDescID := questionFields[0].Descriptor()
	// question.DefaultID holds the default value on creation for the id field.
	question.DefaultID = questionDescID.Default.(func() uuid.UUID)
	surveyHooks := schema.Survey{}.Hooks()
	survey.Hooks[0] = surveyHooks[0]
	surveyFields := schema.Survey{}.Fields()
	_ = surveyFields
	// surveyDescIdentifier is the schema descriptor for identifier field.
	surveyDescIdentifier := surveyFields[1].Descriptor()
	// survey.DefaultIdentifier holds the default value on creation for the identifier field.
	survey.DefaultIdentifier = surveyDescIdentifier.Default.(func() string)
	// surveyDescName is the schema descriptor for name field.
	surveyDescName := surveyFields[2].Descriptor()
	// survey.NameValidator is a validator for the "name" field. It is called by the builders before save.
	survey.NameValidator = surveyDescName.Validators[0].(func(string) error)
	// surveyDescDescription is the schema descriptor for description field.
	surveyDescDescription := surveyFields[3].Descriptor()
	// survey.DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	survey.DescriptionValidator = surveyDescDescription.Validators[0].(func(string) error)
	// surveyDescCreatedAt is the schema descriptor for created_at field.
	surveyDescCreatedAt := surveyFields[4].Descriptor()
	// survey.DefaultCreatedAt holds the default value on creation for the created_at field.
	survey.DefaultCreatedAt = surveyDescCreatedAt.Default.(func() time.Time)
	// surveyDescUpdatedAt is the schema descriptor for updated_at field.
	surveyDescUpdatedAt := surveyFields[5].Descriptor()
	// survey.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	survey.DefaultUpdatedAt = surveyDescUpdatedAt.Default.(func() time.Time)
	// surveyDescID is the schema descriptor for id field.
	surveyDescID := surveyFields[0].Descriptor()
	// survey.DefaultID holds the default value on creation for the id field.
	survey.DefaultID = surveyDescID.Default.(func() uuid.UUID)
	surveyinvitationFields := schema.SurveyInvitation{}.Fields()
	_ = surveyinvitationFields
	// surveyinvitationDescSent is the schema descriptor for sent field.
	surveyinvitationDescSent := surveyinvitationFields[1].Descriptor()
	// surveyinvitation.DefaultSent holds the default value on creation for the sent field.
	surveyinvitation.DefaultSent = surveyinvitationDescSent.Default.(bool)
	// surveyinvitationDescSentTimes is the schema descriptor for sent_times field.
	surveyinvitationDescSentTimes := surveyinvitationFields[2].Descriptor()
	// surveyinvitation.DefaultSentTimes holds the default value on creation for the sent_times field.
	surveyinvitation.DefaultSentTimes = surveyinvitationDescSentTimes.Default.([]string)
	// surveyinvitationDescCreatedAt is the schema descriptor for created_at field.
	surveyinvitationDescCreatedAt := surveyinvitationFields[3].Descriptor()
	// surveyinvitation.DefaultCreatedAt holds the default value on creation for the created_at field.
	surveyinvitation.DefaultCreatedAt = surveyinvitationDescCreatedAt.Default.(func() time.Time)
	// surveyinvitationDescUpdatedAt is the schema descriptor for updated_at field.
	surveyinvitationDescUpdatedAt := surveyinvitationFields[4].Descriptor()
	// surveyinvitation.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	surveyinvitation.DefaultUpdatedAt = surveyinvitationDescUpdatedAt.Default.(func() time.Time)
	surveyquestionanswersFields := schema.SurveyQuestionAnswers{}.Fields()
	_ = surveyquestionanswersFields
	// surveyquestionanswersDescQuestionNum is the schema descriptor for question_num field.
	surveyquestionanswersDescQuestionNum := surveyquestionanswersFields[0].Descriptor()
	// surveyquestionanswers.DefaultQuestionNum holds the default value on creation for the question_num field.
	surveyquestionanswers.DefaultQuestionNum = surveyquestionanswersDescQuestionNum.Default.(int64)
}

const (
	Version = "v0.12.4"                                         // Version of ent codegen.
	Sum     = "h1:LddPnAyxls/O7DTXZvUGDj0NZIdGSu317+aoNLJWbD8=" // Sum of ent codegen.
)
